radianHub/Greenheart-Exchange

force-app/main/default/customMetadata/Universal_App.Flight_Information_Arrival.md-meta.xml
force-app/main/default/customMetadata/Universal_App_Field_Setting.FlightInfo_Flight_Number.md-meta.xml
force-app/main/default/customMetadata/Universal_App_Section.Flight_Info_Arrival_Airline.md-meta.xml
force-app/main/default/customMetadata/Universal_App_Section.Flight_Info_Arrival_Details.md-meta.xml
force-app/main/default/objects/Flight_Information__c/fieldSets/Flight_Info_Arrival_Airline.fieldSet-meta.xml
force-app/main/default/objects/Flight_Information__c/fieldSets/Flight_Info_Arrival_Details.fieldSet-meta.xml

[DevOps Center] Merge WI-010224 to UAT

---

force-app/main/default/customMetadata/Universal_App.Visa_Interview_Outcome.md-meta.xml
force-app/main/default/customMetadata/Universal_App_Field_Setting.VisaInterviewOutcome_Will_you_appeal.md-meta.xml
force-app/main/default/customMetadata/Universal_App_Field_Setting.VisaInterview_Outcome.md-meta.xml
force-app/main/default/customMetadata/Universal_App_Field_Setting.Visa_Interview_Outcome.md-meta.xml
force-app/main/default/customMetadata/Universal_App_Section.Visa_Interview_Appeal.md-meta.xml
force-app/main/default/customMetadata/Universal_App_Section.Visa_Interview_Outcome.md-meta.xml
force-app/main/default/objects/Opportunity/fieldSets/Visa_Interview_Appeal.fieldSet-meta.xml
force-app/main/default/objects/Opportunity/fieldSets/Visa_Interview_Outcome.fieldSet-meta.xml

[DevOps Center] Merge WI-010226 to UAT

---

force-app/main/default/customMetadata/Universal_App.Cross_cultural_Activity.md-meta.xml
force-app/main/default/customMetadata/Universal_App_Field_Setting.CCA_Attendees.md-meta.xml
force-app/main/default/customMetadata/Universal_App_Field_Setting.CCA_Estimated_Impact.md-meta.xml
force-app/main/default/customMetadata/Universal_App_Field_Setting.CCA_Estimated_Local_Audience.md-meta.xml
force-app/main/default/customMetadata/Universal_App_Field_Setting.CCA_General_Overview.md-meta.xml
force-app/main/default/customMetadata/Universal_App_Field_Setting.CCA_International_Estimated_US_Audience.md-meta.xml
force-app/main/default/customMetadata/Universal_App_Field_Setting.CCA_Location.md-meta.xml
force-app/main/default/customMetadata/Universal_App_Field_Setting.CCA_Name_of_International_School.md-meta.xml
force-app/main/default/customMetadata/Universal_App_Field_Setting.CCA_Type_Other.md-meta.xml
force-app/main/default/customMetadata/Universal_App_Section.CCA_Activity_Report.md-meta.xml
force-app/main/default/customMetadata/Universal_App_Section.CCA_Details.md-meta.xml
force-app/main/default/customMetadata/Universal_App_Section.CCA_International_Activity.md-meta.xml
force-app/main/default/customMetadata/Universal_App_Section.CCA_Local_Activity.md-meta.xml
force-app/main/default/customMetadata/Universal_App_Section.CCA_Other_Type_of_Activity.md-meta.xml
force-app/main/default/objects/Cross_Cultural_Activity__c/fieldSets/Activity_Details.fieldSet-meta.xml
force-app/main/default/objects/Cross_Cultural_Activity__c/fieldSets/Activity_Report.fieldSet-meta.xml
force-app/main/default/objects/Cross_Cultural_Activity__c/fieldSets/International_Activity.fieldSet-meta.xml
force-app/main/default/objects/Cross_Cultural_Activity__c/fieldSets/Local_Activity.fieldSet-meta.xml
force-app/main/default/objects/Cross_Cultural_Activity__c/fieldSets/Other_Type_of_Activity.fieldSet-meta.xml

[DevOps Center] Merge WI-010355 to UAT

---

force-app/main/default/customMetadata/Universal_App.J2_Application.md-meta.xml
force-app/main/default/customMetadata/Universal_App_Field_Setting.J2_App_Email_Address.md-meta.xml
force-app/main/default/customMetadata/Universal_App_Field_Setting.J2_App_J2_Plans_to_Work.md-meta.xml
force-app/main/default/customMetadata/Universal_App_Field_Setting.J2_App_Name.md-meta.xml
force-app/main/default/customMetadata/Universal_App_Field_Setting.J2_App_Passport_First_Name.md-meta.xml
force-app/main/default/customMetadata/Universal_App_Field_Setting.J2_App_Passport_Last_Name.md-meta.xml
force-app/main/default/customMetadata/Universal_App_Field_Setting.J2_App_Relationship_to_J1.md-meta.xml
force-app/main/default/customMetadata/Universal_App_Field_Setting.J2_App_Shipping_Address.md-meta.xml
force-app/main/default/customMetadata/Universal_App_Section.J2_App_Birth_Residence.md-meta.xml
force-app/main/default/customMetadata/Universal_App_Section.J2_App_General_Info.md-meta.xml
force-app/main/default/customMetadata/Universal_App_Section.J2_App_Header.md-meta.xml
force-app/main/default/customMetadata/Universal_App_Section.J2_App_Passport_Info.md-meta.xml
force-app/main/default/customMetadata/Universal_App_Section.J2_App_Spouse_Working.md-meta.xml
force-app/main/default/customMetadata/Universal_App_Section.J2_App_Spouse_Working_Message.md-meta.xml
force-app/main/default/objects/Opportunity/fieldSets/J2_App_Birth_Residence.fieldSet-meta.xml
force-app/main/default/objects/Opportunity/fieldSets/J2_App_General_Info.fieldSet-meta.xml
force-app/main/default/objects/Opportunity/fieldSets/J2_App_Passport_Info.fieldSet-meta.xml
force-app/main/default/objects/Opportunity/fieldSets/J2_App_Spouse_Working.fieldSet-meta.xml

[DevOps Center] Merge WI-010363 to UAT

---

force-app/main/default/classes/UniversalApp.cls
force-app/main/default/customMetadata/Universal_App.Arrival_Check_In.md-meta.xml
force-app/main/default/customMetadata/Universal_App.Cross_cultural_Activity.md-meta.xml
force-app/main/default/customMetadata/Universal_App.Flight_Information_Arrival.md-meta.xml
force-app/main/default/customMetadata/Universal_App.J2_Application.md-meta.xml
force-app/main/default/customMetadata/Universal_App.Monthly_Check_In.md-meta.xml
force-app/main/default/customMetadata/Universal_App.Teach_USA_Application.md-meta.xml
force-app/main/default/customMetadata/Universal_App.Terms_and_Conditions.md-meta.xml
force-app/main/default/customMetadata/Universal_App.Visa_Interview_Date.md-meta.xml
force-app/main/default/customMetadata/Universal_App.Visa_Interview_Outcome.md-meta.xml
force-app/main/default/layouts/Universal_App__mdt-Universal App Layout.layout-meta.xml
force-app/main/default/lwc/univApp/univApp.css
force-app/main/default/lwc/univApp/univApp.html
force-app/main/default/lwc/univApp/univApp.js
force-app/main/default/lwc/univApp/univApp.js-meta.xml
force-app/main/default/objects/Opportunity/fieldSets/Visa_Interview_Appeal.fieldSet-meta.xml
force-app/main/default/objects/Universal_App__mdt/fields/ParentOppField__c.field-meta.xml

[DevOps Center] Merge WI-010374 to UAT

---

force-app/main/default/objects/Opportunity/fields/Current_Partner_Linked_Opportunities__c.field-meta.xml
force-app/main/default/objects/Opportunity/listViews/Partners_My_Participants.listView-meta.xml
force-app/main/default/objects/User/fields/Account_Id__c.field-meta.xml

[DevOps Center] Merge WI-010390 to UAT

---

force-app/main/default/customMetadata/Universal_App.Terms_and_Conditions_Host_Schools.md-meta.xml
force-app/main/default/customMetadata/Universal_App_Field_Setting.T_C_HS_Date_Field.md-meta.xml
force-app/main/default/customMetadata/Universal_App_Field_Setting.T_C_HS_Name_Field.md-meta.xml
force-app/main/default/customMetadata/Universal_App_Section.T_Cs_HS_Introduction.md-meta.xml
force-app/main/default/customMetadata/Universal_App_Section.T_Cs_HS_Responsibilities.md-meta.xml
force-app/main/default/customMetadata/Universal_App_Section.T_Cs_HS_Responsibilities_2.md-meta.xml
force-app/main/default/customMetadata/Universal_App_Section.T_Cs_HS_Responsibilities_Regulations.md-meta.xml
force-app/main/default/objects/Account/fieldSets/Blank_Field_Set.fieldSet-meta.xml
force-app/main/default/objects/Account/fieldSets/T_Cs_Name_and_Date.fieldSet-meta.xml
force-app/main/default/objects/Account/fields/Terms_and_Conditions_Full_Name__c.field-meta.xml

[DevOps Center] Merge WI-010403 to UAT

---

force-app/main/default/objects/Program_Renewal__c/fields/Date__c.field-meta.xml

[DevOps Center] Merge WI-010406 to UAT

---

force-app/main/default/lwc/financialFees/financialFees.html
force-app/main/default/lwc/financialFees/financialFees.js
force-app/main/default/lwc/financialFees/financialFees.js-meta.xml

[DevOps Center] Merge WI-010395 to UAT

---

force-app/main/default/classes/DisplayRecordFromFieldSetController.cls
force-app/main/default/classes/DisplayRecordFromFieldSetController.cls-meta.xml
force-app/main/default/classes/DisplayRecordFromFieldSetControllerTest.cls
force-app/main/default/classes/DisplayRecordFromFieldSetControllerTest.cls-meta.xml
force-app/main/default/classes/Fetch.cls
force-app/main/default/classes/Fetch.cls-meta.xml
force-app/main/default/classes/FetchTest.cls
force-app/main/default/classes/FetchTest.cls-meta.xml
force-app/main/default/classes/UsersService.cls
force-app/main/default/lwc/displayRecordFromFieldSet/displayRecordFromFieldSet.css
force-app/main/default/lwc/displayRecordFromFieldSet/displayRecordFromFieldSet.html
force-app/main/default/lwc/displayRecordFromFieldSet/displayRecordFromFieldSet.js
force-app/main/default/lwc/displayRecordFromFieldSet/displayRecordFromFieldSet.js-meta.xml
force-app/main/default/lwc/errorPanel/errorPanel.html
force-app/main/default/lwc/errorPanel/errorPanel.js
force-app/main/default/lwc/errorPanel/errorPanel.js-meta.xml
force-app/main/default/lwc/errorPanel/templates/banner.html
force-app/main/default/lwc/errorPanel/templates/emptyUI.html
force-app/main/default/lwc/errorPanel/templates/inlineMessage.html
force-app/main/default/lwc/errorPanel/templates/noDataIllustration.html
force-app/main/default/lwc/utilities/utilities.js
force-app/main/default/lwc/utilities/utilities.js-meta.xml

[DevOps Center] Merge WI-010393 to UAT

---

force-app/main/default/assignmentRules/Case.assignmentRules-meta.xml
force-app/main/default/objects/Case/businessProcesses/Teacher Changes Reported by Host Schools.businessProcess-meta.xml
force-app/main/default/objects/Case/businessProcesses/Teacher Requests.businessProcess-meta.xml
force-app/main/default/objects/Case/recordTypes/Host_School_Cases.recordType-meta.xml
force-app/main/default/objects/Case/recordTypes/Teacher_Cases.recordType-meta.xml
force-app/main/default/queues/Host_School_Requests.queue-meta.xml
force-app/main/default/queues/Teacher_Requests.queue-meta.xml
force-app/main/default/quickActions/Host_School_Request.quickAction-meta.xml
force-app/main/default/quickActions/Teacher_Request.quickAction-meta.xml
force-app/main/default/standardValueSets/CaseType.standardValueSet-meta.xml

[DevOps Center] Merge WI-010387 to UAT

---

force-app/main/default/customMetadata/Universal_App_Field_Setting.MCI_Address_Update.md-meta.xml
force-app/main/default/customMetadata/Universal_App_Field_Setting.MCI_City_Update.md-meta.xml
force-app/main/default/customMetadata/Universal_App_Field_Setting.MCI_New_Address.md-meta.xml
force-app/main/default/customMetadata/Universal_App_Field_Setting.MCI_State_Update.md-meta.xml
force-app/main/default/customMetadata/Universal_App_Field_Setting.MCI_Zip_Update.md-meta.xml
force-app/main/default/customMetadata/Universal_App_Section.CCA_Details.md-meta.xml
force-app/main/default/customMetadata/Universal_App_Section.CCA_International_Activity.md-meta.xml
force-app/main/default/customMetadata/Universal_App_Section.CCA_Local_Activity.md-meta.xml
force-app/main/default/customMetadata/Universal_App_Section.CCA_Other_Type_of_Activity.md-meta.xml
force-app/main/default/customMetadata/Universal_App_Section.MCI_Address_Has_Updates.md-meta.xml
force-app/main/default/customMetadata/Universal_App_Section.MCI_Address_Updates.md-meta.xml
force-app/main/default/customMetadata/Universal_App_Section.MCI_Employment_Changes.md-meta.xml
force-app/main/default/customMetadata/Universal_App_Section.MCI_Employment_Has_Changes.md-meta.xml
force-app/main/default/customMetadata/Universal_App_Section.MCI_Health_Overall.md-meta.xml
force-app/main/default/customMetadata/Universal_App_Section.MCI_Health_Reason.md-meta.xml
force-app/main/default/customMetadata/Universal_App_Section.MCI_Major_Issues.md-meta.xml
force-app/main/default/customMetadata/Universal_App_Section.MCI_Major_Issues_Details.md-meta.xml
force-app/main/default/customMetadata/Universal_App_Section.MCI_Safety_Concerns.md-meta.xml
force-app/main/default/customMetadata/Universal_App_Section.MCI_Safety_Has_Concerns.md-meta.xml
force-app/main/default/customMetadata/Universal_App_Section.Visa_Interview_Appeal.md-meta.xml
force-app/main/default/customMetadata/Universal_App_Section.Visa_Interview_Outcome.md-meta.xml
force-app/main/default/lwc/univAppContainerConditional/univAppContainerConditional.html
force-app/main/default/lwc/univAppContainerConditional/univAppContainerConditional.js
force-app/main/default/lwc/univAppContainerConditional/univAppContainerConditional.js-meta.xml

[DevOps Center] Merge WI-010407 to UAT

---

force-app/main/default/classes/DisplayRecordFromFieldSetController.cls
force-app/main/default/classes/DisplayRecordFromFieldSetControllerTest.cls
force-app/main/default/classes/UsersService.cls
force-app/main/default/classes/UsersServiceTest.cls
force-app/main/default/lwc/displayRecordFromFieldSet/displayRecordFromFieldSet.html
force-app/main/default/lwc/displayRecordFromFieldSet/displayRecordFromFieldSet.js
force-app/main/default/lwc/displayRecordFromFieldSet/displayRecordFromFieldSet.js-meta.xml

[DevOps Center] Merge WI-010430 to UAT

---

force-app/main/default/lwc/univApp/univApp.js

[DevOps Center] Merge WI-010450 to UAT

---

force-app/main/default/lwc/filesUpload/filesUpload.js
force-app/main/default/lwc/univAppContainerConditional/univAppContainerConditional.html
force-app/main/default/lwc/univAppContainerConditional/univAppContainerConditional.js
force-app/main/default/lwc/univAppProgressIndicator/univAppProgressIndicator.js

[DevOps Center] Merge WI-010454 to UAT

---

force-app/main/default/classes/CommunityUtility.cls
force-app/main/default/classes/CommunityUtility.cls-meta.xml
force-app/main/default/classes/CommunityUtilityTest.cls
force-app/main/default/classes/CommunityUtilityTest.cls-meta.xml
force-app/main/default/classes/GH_SendReminderForPlacementAgreementTest.cls
force-app/main/default/classes/GH_SendReminderForPlacementAgreementTest.cls-meta.xml
force-app/main/default/classes/OpportunityService.cls
force-app/main/default/classes/OpportunityServiceTest.cls
force-app/main/default/classes/OpportunityServiceTest.cls-meta.xml
force-app/main/default/classes/OpportunityTriggerHandler.cls
force-app/main/default/classes/RemoveSpecialCharacterTest.cls
force-app/main/default/classes/RemoveSpecialCharacterTest.cls-meta.xml
force-app/main/default/classes/RequiredFieldsCache.cls

[DevOps Center] Merge WI-010456 to UAT

---

force-app/main/default/classes/OpportunityTriggerHandler.cls

[DevOps Center] Merge WI-010461 to UAT

---

force-app/main/default/customMetadata/Universal_App_Field_Setting.SA_GHT.md-meta.xml
force-app/main/default/customMetadata/Universal_App_Field_Setting.SA_HSP.md-meta.xml

[DevOps Center] Merge WI-010471 to UAT

---

force-app/main/default/lwc/univApp/univApp.js

[DevOps Center] Merge WI-010473 to UAT

---

force-app/main/default/classes/CommunityUtility.cls
force-app/main/default/classes/CommunityUtilityTest.cls
force-app/main/default/classes/OpportunityService.cls
force-app/main/default/groups/Teach_USA_Host_School.group-meta.xml
force-app/main/default/groups/Teach_USA_Partners.group-meta.xml
force-app/main/default/groups/Teach_USA_Teachers.group-meta.xml

[DevOps Center] Merge WI-010475 to UAT

---

force-app/main/default/objects/Account/fieldSets/Display_Fields_School_Application.fieldSet-meta.xml
force-app/main/default/objects/Account/fieldSets/Display_Fields_School_Renewal.fieldSet-meta.xml

[DevOps Center] Merge WI-010479 to UAT

---

force-app/main/default/customMetadata/Universal_App.Terms_and_Conditions.md-meta.xml
force-app/main/default/customMetadata/Universal_App_Section.TC_Signature.md-meta.xml
force-app/main/default/customMetadata/Universal_App_Section.T_C_Public_Health_Conditions_2.md-meta.xml
force-app/main/default/objects/Opportunity/fieldSets/TC_Signature.fieldSet-meta.xml
force-app/main/default/objects/Opportunity/fields/TC_Signed_FullName__c.field-meta.xml
force-app/main/default/objects/Universal_App_Section__mdt/listViews/Teacher_TC.listView-meta.xml

[DevOps Center] Merge WI-010484 to UAT

---

force-app/main/default/customMetadata/Universal_App_Section.SR_Terms_and_Conditions.md-meta.xml
force-app/main/default/customMetadata/Universal_App_Section.SR_Terms_and_Conditions2.md-meta.xml
force-app/main/default/customMetadata/Universal_App_Section.SR_Terms_and_Conditions3.md-meta.xml
force-app/main/default/customMetadata/Universal_App_Section.SR_Terms_and_Conditions4.md-meta.xml

[DevOps Center] Merge WI-010488 to UAT

---

force-app/main/default/lwc/univAppContainerConditional/univAppContainerConditional.js
force-app/main/default/lwc/univAppContainerConditional/univAppContainerConditional.js-meta.xml

[DevOps Center] Merge WI-010565 to UAT

---

force-app/main/default/flows/Screen_Flow_Teacher_Program_Extension.flow-meta.xml
force-app/main/default/flows/Screen_Flow_Teacher_Program_Renewal.flow-meta.xml
force-app/main/default/objects/Document__c/fields/Program_Extension__c.field-meta.xml
force-app/main/default/objects/Document__c/fields/Program_Renewal__c.field-meta.xml

[DevOps Center] Merge WI-010573 to UAT

---

force-app/main/default/lwc/univAppContainerConditional/univAppContainerConditional.html

[DevOps Center] Merge WI-010574 to UAT

---

force-app/main/default/lwc/filesUpload/filesUpload.html
force-app/main/default/lwc/filesUpload/filesUpload.js
force-app/main/default/lwc/filesUpload/filesUpload.js-meta.xml

[DevOps Center] Merge WI-010587 to UAT

---

force-app/main/default/classes/UniversalApp.cls
force-app/main/default/customMetadata/Universal_App.J2_Application.md-meta.xml
force-app/main/default/objects/Opportunity/fieldSets/J2_App_General_Info.fieldSet-meta.xml

[DevOps Center] Merge WI-010602 to UAT

---

force-app/main/default/lwc/filesUpload/filesUpload.html
force-app/main/default/lwc/filesUpload/filesUpload.js

[DevOps Center] Merge WI-010603 to UAT

---

force-app/main/default/lwc/displayRecordFromFieldSet/displayRecordFromFieldSet.js
force-app/main/default/lwc/displayRecordFromFieldSet/displayRecordFromFieldSet.js-meta.xml

[DevOps Center] Merge WI-010604 to UAT

---

force-app/main/default/flows/Screen_Flow_Teacher_Program_Extension.flow-meta.xml
force-app/main/default/flows/Screen_Flow_Teacher_Program_Renewal.flow-meta.xml

[DevOps Center] Merge WI-010616 to UAT

---

force-app/main/default/flows/Orientation_Quiz.flow-meta.xml
force-app/main/default/flows/Screen_Flow_Teacher_Program_Extension.flow-meta.xml
force-app/main/default/flows/Screen_Flow_Teacher_Program_Renewal.flow-meta.xml

[DevOps Center] Merge WI-010621 to UAT

---

force-app/main/default/classes/UniversalApp.cls
force-app/main/default/layouts/Universal_App__mdt-Universal App Layout.layout-meta.xml
force-app/main/default/lwc/univApp/univApp.html
force-app/main/default/lwc/univApp/univApp.js
force-app/main/default/lwc/univApp/univApp.js-meta.xml
force-app/main/default/objects/Universal_App__mdt/fields/isSaveForLaterEnabled__c.field-meta.xml

[DevOps Center] Merge WI-010612 to UAT

---

force-app/main/default/classes/UniversalApp.cls
force-app/main/default/lwc/univApp/univApp.html
force-app/main/default/lwc/univApp/univApp.js
force-app/main/default/lwc/univApp/univApp.js-meta.xml

[DevOps Center] Merge WI-010640 to UAT

---

force-app/main/default/flows/Screen_Flow_Teacher_Program_Renewal.flow-meta.xml

[DevOps Center] Merge WI-010644 to UAT

---

force-app/main/default/classes/UniversalApp_Test.cls

[DevOps Center] Merge WI-010681 to UAT

---

force-app/main/default/classes/UniversalApp.cls
force-app/main/default/layouts/Universal_App__mdt-Universal App Layout.layout-meta.xml
force-app/main/default/objects/Universal_App__mdt/fields/isHideFinishButton__c.field-meta.xml

[DevOps Center] Merge WI-010683 to UAT

---

force-app/main/default/customMetadata/Universal_App_Field_Setting.SR_Start_Date_Latest.md-meta.xml

[DevOps Center] Merge WI-010613 to UAT

---

force-app/main/default/lwc/financialFees/financialFees.js

[DevOps Center] Merge WI-010685 to UAT
